local colorscheme = require("base.theme").Theme({
  name = "base-poimandres",
  background = "dark",
})

colorscheme.theme = {
  base00 = "#1b1e28",
  base01 = "#2b3040",
  base02 = "#32384a",
  base03 = "#3b4258",
  base04 = "#48506a",
  base05 = "#a6accd",
  base06 = "#b6d7f4",
  base07 = "#ffffff",
  base08 = "#a6accd",
  base09 = "#d0679d",
  base0A = "#5de4c7",
  base0B = "#5de4c7",
  base0C = "#89ddff",
  base0D = "#add7ff",
  base0E = "#91b4d5",
  base0F = "#ffffff",
}

colorscheme.colors = {
  bg_1 = "#222633",
  bg_2 = "#2b3040",
  bg_3 = "#32384a",
  bg_4 = "#303340",
  bg_folder = "#91b4d5",
  bg_light = "#32384a",
  bg_pmenu = "#5fb3a1",
  bg_statusline = "#222633",
  black = "#1b1e28",
  blue = "#89ddff",
  cyan = "#92e0ff",
  dark_black = "#171922",
  dark_purple = "#b6d7f4",
  green = "#5fb3a1",
  grey = "#48506a",
  light_green = "#71bbab",
  light_grey_1 = "#515977",
  light_grey_2 = "#5d678a",
  light_grey_3 = "#657096",
  light_pink = "#fae4fc",
  line = "#303340",
  nord_blue = "#91b4d5",
  orange = "#91b4d5",
  pink = "#fcc5e9",
  purple = "#a6accd",
  red = "#d0679d",
  sun = "#fff691",
  teal = "#5de4c7",
  white = "#e4f0fb",
  yellow = "#fffac2",
}

colorscheme.extra = {
  ogwhite = "#ffffff",
  seablue = "#add7ff",
}

colorscheme.polish = {
  ["@constant"] = { fg = "#E4F0FB" },
  ["@constant.builtin"] = { fg = "#ADD7FF" },
  ["@constructor"] = { fg = colorscheme.colors.light_grey_1 },
  ["@constructor.tsx"] = { link = "Tag" },
  ["@function.call"] = { fg = "#A6ACCD" },
  ["@keyword.operator"] = { fg = "#ADD7FF" },
  ["@keyword.return"] = { fg = "#5FB3A1" },
  ["@none"] = { fg = colorscheme.colors.dark_purple },
  ["@operator"] = { fg = "#91B4D5" },
  ["@property"] = { fg = "#ADD7FF" },
  ["@punctuation.bracket"] = { fg = "#A6ACCD" },
  ["@punctuation.delimiter"] = { fg = "#ADD7FF" },
  ["@punctuation.special"] = { fg = "#A6ACCD" },
  ["@tag.attribute"] = { link = "", fg = "#A6ACCD", italic = true },
  ["@type.builtin"] = { link = "Boolean" },
  ["@variable"] = { fg = colorscheme.extra.ogwhite },
  ["@variable.builtin"] = { fg = colorscheme.colors.dark_purple },
  CmpItemAbbr = { fg = "#A6ACCD" },
  CmpItemAbbrMatch = { fg = colorscheme.colors.dark_purple },
  CmpSel = { link = "", bg = colorscheme.colors.bg_light },
  Include = { fg = "#89DDFF" },
  Label = { fg = "#ADD7FF" },
  St_CommandMode = { fg = "#5DE4C7" },
  TelescopeMatching = { fg = "#5DE4C7" },
  Type = { fg = "#A6ACCD" },
}

colorscheme:paint()
