local colorscheme = require("base.theme").Theme({
  name = "base-material-darker",
  background = "dark",
})

colorscheme.theme = {
  base00 = "#212121",
  base01 = "#292929",
  base02 = "#303030",
  base03 = "#383838",
  base04 = "#404040",
  base05 = "#dff0f0",
  base06 = "#e6f7f7",
  base07 = "#eeffff",
  base08 = "#b0bec5",
  base09 = "#f78c6c",
  base0A = "#ffcb6b",
  base0B = "#c3e88d",
  base0C = "#c3e88d",
  base0D = "#82aaff",
  base0E = "#c792ea",
  base0F = "#f07178",
}

colorscheme.colors = {
  bg_1 = "#292929",
  bg_2 = "#303030",
  bg_3 = "#383838",
  bg_4 = "#404040",
  bg_folder = "#6e98eb",
  bg_light = "#323232",
  bg_pmenu = "#6e98eb",
  bg_statusline = "#262626",
  black = "#212121",
  blue = "#82aaff",
  cyan = "#89ddff",
  dark_black = "#191919",
  dark_purple = "#b480d6",
  green = "#c3e88d",
  grey = "#4a4a4a",
  light_green = "#c3e88d",
  light_grey_1 = "#545454",
  light_grey_2 = "#5e5e5e",
  light_grey_3 = "#6b6b6b",
  light_pink = "#ffadff",
  line = "#383838",
  nord_blue = "#6e98eb",
  orange = "#f78c6c",
  pink = "#da70ca",
  purple = "#c792ea",
  red = "#f07178",
  sun = "#e6b455",
  teal = "#abcf76",
  white = "#eeffff",
  yellow = "#ffcb6b",
}

colorscheme.polish = {
  ["@attribute"] = { fg = colorscheme.colors.purple },
  ["@conditional.ternary"] = { fg = colorscheme.colors.cyan },
  ["@constant"] = { fg = colorscheme.colors.yellow },
  ["@constant.builtin"] = { link = "@constant" },
  ["@constructor"] = { fg = colorscheme.colors.cyan },
  ["@delimiter"] = { fg = "#DA70CA" },
  ["@function"] = { fg = colorscheme.colors.blue },
  ["@function.macro"] = {},
  ["@keyword"] = { fg = colorscheme.colors.cyan },
  ["@keyword.exception"] = { fg = colorscheme.colors.purple },
  ["@keyword.repeat"] = { fg = colorscheme.colors.purple },
  ["@lsp.type.annotation"] = { fg = colorscheme.colors.purple },
  ["@lsp.type.class"] = { fg = colorscheme.colors.yellow },
  ["@lsp.type.enum"] = { link = "@lsp.type.class" },
  ["@lsp.type.enumMember"] = { link = "@lsp.type.property" },
  ["@lsp.type.interface"] = { italic = true, fg = colorscheme.colors.green },
  ["@lsp.type.method"] = { fg = colorscheme.colors.blue },
  ["@lsp.type.modifier"] = { fg = colorscheme.colors.purple },
  ["@lsp.type.namespace"] = { link = "@lsp.type.class" },
  ["@lsp.type.parameter"] = { fg = colorscheme.colors.orange },
  ["@lsp.type.property"] = { fg = colorscheme.colors.white },
  ["@lsp.type.variable"] = { fg = colorscheme.colors.white },
  ["@lsp.typemod.class.constructor"] = { link = "@lsp.type.method" },
  ["@lsp.typemod.record"] = { link = "@lsp.type.class" },
  ["@module"] = { fg = colorscheme.colors.yellow },
  ["@operator"] = { fg = colorscheme.colors.cyan },
  ["@parenthesis"] = { link = "@punctuation.bracket" },
  ["@punctuation.bracket"] = { fg = "#DA70CA" },
  ["@punctuation.delimiter"] = { fg = "#DA70CA" },
  ["@string"] = { fg = colorscheme.colors.green },
  ["@type.qualifier"] = { fg = colorscheme.colors.cyan },
  ["@variable.member"] = { fg = colorscheme.colors.white },
  Identifier = { fg = colorscheme.colors.white },
  Include = { fg = colorscheme.colors.purple },
  Number = { fg = colorscheme.colors.orange },
  Structure = { fg = colorscheme.colors.green },
  TelescopeMatching = {},
  Type = { fg = colorscheme.colors.purple },
}

colorscheme:paint()
