local colorscheme = require("base.theme").Theme({
  name = "base-material-deep-ocean",
  background = "dark",
})

colorscheme.theme = {
  base00 = "#0f111a",
  base01 = "#23293e",
  base02 = "#2d3550",
  base03 = "#374162",
  base04 = "#3c476b",
  base05 = "#eeffff",
  base06 = "#a5a9b5",
  base07 = "#b5b8c1",
  base08 = "#f07178",
  base09 = "#f78c6c",
  base0A = "#ffcb6b",
  base0B = "#c3e88d",
  base0C = "#89ddff",
  base0D = "#82aaff",
  base0E = "#c792ea",
  base0F = "#f07178",
}

colorscheme.colors = {
  bg_1 = "#191d2c",
  bg_2 = "#23293e",
  bg_3 = "#2d3550",
  bg_4 = "#374162",
  bg_folder = "#6e98eb",
  bg_light = "#22283d",
  bg_pmenu = "#84ffff",
  bg_statusline = "#181c2b",
  black = "#0f111a",
  blue = "#82aaff",
  cyan = "#89ddff",
  dark_black = "#0a0b14",
  dark_purple = "#a652de",
  green = "#c3e88d",
  grey = "#3c476b",
  light_green = "#81bf27",
  light_grey_1 = "#46537d",
  light_grey_2 = "#505f8f",
  light_grey_3 = "#5a6ba1",
  light_pink = "#f6aaae",
  line = "#313855",
  nord_blue = "#6e98eb",
  orange = "#f78c6c",
  pink = "#f6aaae",
  purple = "#c792ea",
  red = "#f07178",
  sun = "#ffc14e",
  teal = "#80cbc4",
  white = "#eeffff",
  yellow = "#ffcb6b",
}

colorscheme.polish = {
  ["@function.macro"] = { fg = colorscheme.colors.pink },
  ["@keyword.storage"] = { fg = colorscheme.colors.purple },
  ["@module"] = { fg = colorscheme.colors.white },
  ["@operator"] = { fg = colorscheme.colors.cyan },
  ["@punctuation.bracket"] = { fg = colorscheme.colors.cyan },
  ["@punctuation.delimiter"] = { fg = colorscheme.colors.cyan },
  ["@punctuation.special"] = { fg = colorscheme.colors.teal },
  ["@type.builtin"] = { fg = colorscheme.colors.purple },
  ["@variable"] = { fg = colorscheme.colors.white },
  ["@variable.member"] = { fg = colorscheme.colors.white },
  ["@variable.parameter"] = { fg = colorscheme.colors.orange },
  Define = { fg = colorscheme.colors.blue },
  Repeat = { fg = colorscheme.colors.purple },
  StorageClass = { fg = colorscheme.colors.purple },
  TelescopeSelection = { bg = colorscheme.colors.bg_2, fg = colorscheme.colors.blue },
}

colorscheme:paint()
