local M = {}

---comment
---@param theme Base46ThemePalette
---@param colors Base46ThemeColors
---@return table<string, Base46Color>
M.highlights = function(theme, colors)
  return {
    ["@annotation"] = { fg = theme.base0F },
    ["@attribute"] = { fg = theme.base0A },
    ["@character"] = { fg = theme.base08 },
    ["@character.special"] = { fg = theme.base08 },
    ["@comment"] = { fg = colors.light_grey_3, italic = true },
    ["@comment.error"] = { fg = colors.bg_1, bg = colors.red },
    ["@comment.hint"] = { fg = colors.bg_1, bg = colors.white },
    ["@comment.info"] = { fg = colors.bg_1, bg = colors.white },
    ["@comment.note"] = { fg = colors.bg_1, bg = colors.white },
    ["@comment.todo"] = { fg = colors.grey, bg = colors.white },
    ["@comment.warning"] = { fg = colors.bg_1, bg = theme.base09 },
    ["@constant"] = { fg = theme.base08 },
    ["@constant.builtin"] = { fg = theme.base09 },
    ["@constant.macro"] = { fg = theme.base08 },
    ["@constructor"] = { fg = theme.base0C },
    ["@definition"] = { sp = theme.base04, underline = true },
    ["@diff.delta"] = { fg = colors.light_grey_3 },
    ["@diff.minus"] = { fg = colors.red },
    ["@diff.plus"] = { fg = colors.green },
    ["@error"] = { fg = theme.base08 },
    ["@function"] = { fg = theme.base0D },
    ["@function.builtin"] = { fg = theme.base0D },
    ["@function.call"] = { fg = theme.base0D },
    ["@function.macro"] = { fg = theme.base08 },
    ["@function.method"] = { fg = theme.base0D },
    ["@function.method.call"] = { fg = theme.base0D },
    ["@keyword"] = { fg = theme.base0E, italic = true },
    ["@keyword.conditional"] = { fg = theme.base0E },
    ["@keyword.conditional.ternary"] = { fg = theme.base0E },
    ["@keyword.directive"] = { fg = theme.base0A },
    ["@keyword.directive.define"] = { fg = theme.base0E },
    ["@keyword.exception"] = { fg = theme.base08 },
    ["@keyword.function"] = { fg = theme.base0E, italic = true },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { fg = theme.base0E },
    ["@keyword.repeat"] = { fg = theme.base0A, italic = true },
    ["@keyword.return"] = { fg = theme.base0E, italic = true },
    ["@keyword.storage"] = { fg = theme.base0A },
    ["@markup.heading"] = { fg = colors.orange, bold = true },
    ["@markup.heading.1"] = { fg = colors.red, bold = true },
    ["@markup.heading.2"] = { fg = colors.orange, bold = true },
    ["@markup.heading.3"] = { fg = colors.yellow, bold = true },
    ["@markup.heading.4"] = { fg = colors.green, bold = true },
    ["@markup.heading.5"] = { fg = colors.cyan, bold = true },
    ["@markup.heading.6"] = { fg = colors.blue, bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = theme.base08 },
    ["@markup.link.label"] = { fg = theme.base0C },
    ["@markup.link.url"] = { fg = theme.base09, italic = true, underline = true },
    ["@markup.list"] = { fg = theme.base08 },
    ["@markup.list.checked"] = { fg = colors.yellow, bold = true },
    ["@markup.list.unchecked"] = { fg = colors.light_grey_1, bold = true },
    ["@markup.math"] = { fg = colors.light_green, bg = colors.bg_3 },
    ["@markup.quote"] = { bg = colors.bg_3 },
    ["@markup.raw"] = { fg = theme.base09, bg = colors.bg_3 },
    ["@markup.raw.block"] = { fg = theme.base09 },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@module"] = { fg = theme.base08 },
    ["@module.builtin"] = { fg = theme.base08 },
    ["@none"] = { fg = theme.base05 },
    ["@number.float"] = { fg = theme.base09 },
    ["@operator"] = { fg = theme.base05 },
    ["@property"] = { fg = theme.base08 },
    ["@punctuation.bracket"] = { fg = theme.base0F },
    ["@punctuation.delimiter"] = { fg = theme.base0F },
    ["@punctuation.special"] = { fg = theme.base08 },
    ["@reference"] = { fg = theme.base05 },
    ["@scope"] = { bold = true },
    ["@string"] = { fg = theme.base0B },
    ["@string.escape"] = { fg = theme.base0C },
    ["@string.regexp"] = { fg = theme.base0C },
    ["@string.special.symbol"] = { fg = theme.base0B },
    ["@string.special.url"] = { fg = theme.base09, underline = true },
    ["@tag"] = { fg = theme.base0A },
    ["@tag.attribute"] = { fg = theme.base08 },
    ["@tag.delimiter"] = { fg = theme.base0F },
    ["@text"] = { fg = theme.base05 },
    ["@text.emphasis"] = { fg = theme.base09 },
    ["@text.strike"] = { fg = theme.base0F, strikethrough = true },
    ["@type.builtin"] = { fg = theme.base0A },
    ["@variable"] = { fg = theme.base05 },
    ["@variable.builtin"] = { fg = theme.base09 },
    ["@variable.member"] = { fg = theme.base08 },
    ["@variable.member.key"] = { fg = theme.base08 },
    ["@variable.parameter"] = { fg = theme.base08, italic = true },
  }
end

return M
